### ISSUE TITLE
sort issue with single sample vcf

### ISSUE THREAD

**Issue by silviatgl** [a-xavier/tapes#10]
Dear all, 

I'm having a few issues when trying to use tapes. I finally was able to use it to annotate a test sample vcf and I wanted to sort it to see if everything was now working correctly before starting with my whole set of samples. And is not letting me do anything. It kills de process without throwing any concrete error: 

<img width="929" alt="Capture" src="https://user-images.githubusercontent.com/63717815/98667648-f9c83180-234e-11eb-8dc3-841bab1ad59e.PNG">

You can see in the image the vcf was just generated, then I had 2 issues where the problem was a mistake in the extension name of the output. 

But after that you can see how I try 3 times with different sort options and the process is killed with no further explanation, 

I'm running on a virtual ubuntu machine with 4gb ram. The host is windows with 8gb of actual ram. Might be that in needs more ram?

Any help would be extremely useful

Thank you and kindest regards

**Comment by SouzaBB** [comment]
Hi Silvia. It seems that you're running out of memory for this process. Can you see if there's any message on `/var/log/messages`?

**Comment by silviatgl** [comment]
yeah it was an issue of my ram. thanks!
